lines = [
"import Hero from '@/components/components/marketing/Hero';",
"import FeatureCard from '@/components/components/marketing/FeatureCard';",
"import Step from '@/components/components/marketing/Step';",
"import PricingCard from '@/components/components/marketing/PricingCard';",
"import CTASection from '@/components/components/marketing/CTASection';",
"import FAQItem from '@/components/components/marketing/FAQItem';",
"import { Badge } from '@/components/ui/badge';",
"import Link from 'next/link';",
"",
"export default function LandingPage() {",
"  return (",
"    <div className='flex flex-col min-h-screen bg-background'>",
"      <Hero />",
"",
"      <section className='py-24 px-4 bg-muted/30'>",
"        <div className='container mx-auto max-w-5xl'>",
"          <div className='text-center mb-16 space-y-4'>",
"            <Badge variant='outline' className='text-urgent border-urgent font-medium'>The Problem</Badge>",
"            <h2 className='text-3xl font-heading font-bold tracking-tight text-foreground lg:text-5xl'>Every missed call is a job that went to someone else.</h2>",
"            <p className='text-muted-foreground text-lg max-w-2xl mx-auto'>You're under a sink, in a crawlspace, or driving. By the time you check voicemail, the customer has already called the next person on Google.</p>",
"          </div>",
"          <div className='grid grid-cols-1 md:grid-cols-2 gap-8'>",
"            <FeatureCard urgent title='The Voicemail Gap' description='Customers rarely leave voicemails anymore. They just hang up and call the next pro.' benefit='Instant SMS responses keep the lead warm.' />",
"            <FeatureCard urgent title='Phone Tag Fatigue' description='Spending your evenings playing phone tag just to confirm a Tuesday appointment.' benefit='Auto-confirmations handle the back-and-forth.' />",
"            <FeatureCard urgent title='The Double-Book' description='Managing appointments across a notebook, a phone, and memory leads to costly errors.' benefit='Real-time Google Calendar sync prevents overlaps.' />",
"            <FeatureCard urgent title='Reschedule Chaos' description='A simple reschedule request turns into a 4-hour conversation.' benefit='Reschedules handled via SMS without the phone tag.' />",
"          </div>",
"        </div>",
"      </section>",
"",
"      <section className='py-24 px-4'>",
"        <div className='container mx-auto max-w-6xl'>",
"          <div className='text-center mb-16 space-y-4'>",
"            <Badge variant='outline' className='text-primary border-primary font-medium'>The Solution</Badge>",
"            <h2 className='text-3xl font-heading font-bold tracking-tight text-foreground lg:text-5xl'>Your business, on autopilot.</h2>",
"            <p className='text-muted-foreground text-lg max-w-2xl mx-auto'>TradeScheduler acts as your AI dispatch assistant, ensuring no lead goes cold and every job is confirmed.</p>",
"          </div>",
"          <div className='grid grid-cols-1 md:grid-cols-3 gap-6'>",
"            <FeatureCard title='Missed Calls to Booked Jobs' description='When you can't pick up, we respond via SMS to qualify the lead and suggest times.' benefit='Capture leads while you work.' />",
